### ISSUE TITLE
API UI middleware oAuth2 callback not working

### ISSUE THREAD

**Issue by deborggraever** [go-openapi/runtime#255]
For my project i'm using go-openapi/runtime to host api documents in my project, but run into some issues trying to add oauth2.
I tried both swagger and rapidoc and both give a 404 after redirecting back from the authentication.

API doc initialization:
https://github.com/deb-ict/cloudbm-community/blob/features/authentication/cmd/webhost/main.go
```
	contactSwaggerOptions := middleware.SwaggerUIOpts{
		BasePath: "/api/contact",
		Path:     "swagger",
		SpecURL:  "/api/spec/contacts.yaml",
	}
	contactSwaggerHandler := middleware.SwaggerUI(contactSwaggerOptions, nil)
	router.Handle("/api/contact/swagger", contactSwaggerHandler)
```
```
	contactRapidocOptions := middleware.RapiDocOpts{
		BasePath: "/api/contact",
		Path:     "docs",
		SpecURL:  "/api/spec/contacts.yaml",
	}
	contactRapidocHandler := middleware.RapiDoc(contactRapidocOptions, nil)
	router.Handle("/api/contact/docs", contactRapidocHandler)
```

API spec: (generated by go-swagger)
https://github.com/deb-ict/cloudbm-community/blob/features/authentication/api/contacts.yaml
```
securityDefinitions:
    oauth:
        authorizationUrl: /auth/v1/authorize
        flow: implicit
        scopes:
            contacts.metadata.read: Read contacts metadata
            contacts.metadata.write: Write contacts metadata
            contacts.read: Read company and contact person information
            contacts.write: Write company and contact person information
        tokenUrl: /auth/v1/token
        type: oauth2
```

For swagger, after authentication, i get a 404 Page not found error on `oauth2-redirect.html`
Callback url:
`http://localhost:8080/api/contact/oauth2-redirect.html?access_token=mytoken&expires_in=3600&state=TW9uIE9jdCAxNyAyMDIyIDIzOjI0OjU2IEdNVCswMjAwIChDZW50cmFsIEV1cm9wZWFuIFN1bW1lciBUaW1lKQ%3D%3D&token_type=bearer`

For rapidoc, after authentication, i get a 404 Page not found on `oauth-receiver.html`
Callback url:
`http://localhost:8080/api/contact/oauth-receiver.html?access_token=mytoken&expires_in=3600&state=x2kzyce&token_type=bearer
`

As for rapidoc, the authentication endpoints goes to `/api/contact/auth/v1/authorize` instead of `/auth/v1/authorize` like swagger does
